# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='userinfo.proto',
  package='UserInfo',
  syntax='proto3',
  serialized_options=_b('\252\002\nXXXService'),
  serialized_pb=_b('\n\x0euserinfo.proto\x12\x08UserInfo\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"N\n\x10GetUserByIdRelpy\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\x03\".\n\x12GetUserListRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xa6\x01\n\x10GetUserListReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x30\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\".UserInfo.GetUserListReply.MsgItem\x1a\x45\n\x07MsgItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\x03\",\n\x0fSaveUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"*\n\rSaveUserReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2\xdd\x01\n\x0fUserInfoService\x12\x45\n\x07GetList\x12\x1c.UserInfo.GetUserListRequest\x1a\x1a.UserInfo.GetUserListReply\"\x00\x12\x45\n\x07GetById\x12\x1c.UserInfo.GetUserByIdRequest\x1a\x1a.UserInfo.GetUserByIdRelpy\"\x00\x12<\n\x04Save\x12\x19.UserInfo.SaveUserRequest\x1a\x17.UserInfo.SaveUserReply\"\x00\x42\r\xaa\x02\nXXXServiceb\x06proto3')
)




_GETUSERBYIDREQUEST = _descriptor.Descriptor(
  name='GetUserByIdRequest',
  full_name='UserInfo.GetUserByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserInfo.GetUserByIdRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=60,
)


_GETUSERBYIDRELPY = _descriptor.Descriptor(
  name='GetUserByIdRelpy',
  full_name='UserInfo.GetUserByIdRelpy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserInfo.GetUserByIdRelpy.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserInfo.GetUserByIdRelpy.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='UserInfo.GetUserByIdRelpy.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='UserInfo.GetUserByIdRelpy.create_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=140,
)


_GETUSERLISTREQUEST = _descriptor.Descriptor(
  name='GetUserListRequest',
  full_name='UserInfo.GetUserListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserInfo.GetUserListRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserInfo.GetUserListRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=188,
)


_GETUSERLISTREPLY_MSGITEM = _descriptor.Descriptor(
  name='MsgItem',
  full_name='UserInfo.GetUserListReply.MsgItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserInfo.GetUserListReply.MsgItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserInfo.GetUserListReply.MsgItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='UserInfo.GetUserListReply.MsgItem.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='UserInfo.GetUserListReply.MsgItem.create_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=357,
)

_GETUSERLISTREPLY = _descriptor.Descriptor(
  name='GetUserListReply',
  full_name='UserInfo.GetUserListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='UserInfo.GetUserListReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='UserInfo.GetUserListReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='UserInfo.GetUserListReply.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETUSERLISTREPLY_MSGITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=357,
)


_SAVEUSERREQUEST = _descriptor.Descriptor(
  name='SaveUserRequest',
  full_name='UserInfo.SaveUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UserInfo.SaveUserRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='UserInfo.SaveUserRequest.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=403,
)


_SAVEUSERREPLY = _descriptor.Descriptor(
  name='SaveUserReply',
  full_name='UserInfo.SaveUserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='UserInfo.SaveUserReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='UserInfo.SaveUserReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=447,
)

_GETUSERLISTREPLY_MSGITEM.containing_type = _GETUSERLISTREPLY
_GETUSERLISTREPLY.fields_by_name['data'].message_type = _GETUSERLISTREPLY_MSGITEM
DESCRIPTOR.message_types_by_name['GetUserByIdRequest'] = _GETUSERBYIDREQUEST
DESCRIPTOR.message_types_by_name['GetUserByIdRelpy'] = _GETUSERBYIDRELPY
DESCRIPTOR.message_types_by_name['GetUserListRequest'] = _GETUSERLISTREQUEST
DESCRIPTOR.message_types_by_name['GetUserListReply'] = _GETUSERLISTREPLY
DESCRIPTOR.message_types_by_name['SaveUserRequest'] = _SAVEUSERREQUEST
DESCRIPTOR.message_types_by_name['SaveUserReply'] = _SAVEUSERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetUserByIdRequest = _reflection.GeneratedProtocolMessageType('GetUserByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERBYIDREQUEST,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo.GetUserByIdRequest)
  })
_sym_db.RegisterMessage(GetUserByIdRequest)

GetUserByIdRelpy = _reflection.GeneratedProtocolMessageType('GetUserByIdRelpy', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERBYIDRELPY,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo.GetUserByIdRelpy)
  })
_sym_db.RegisterMessage(GetUserByIdRelpy)

GetUserListRequest = _reflection.GeneratedProtocolMessageType('GetUserListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERLISTREQUEST,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo.GetUserListRequest)
  })
_sym_db.RegisterMessage(GetUserListRequest)

GetUserListReply = _reflection.GeneratedProtocolMessageType('GetUserListReply', (_message.Message,), {

  'MsgItem' : _reflection.GeneratedProtocolMessageType('MsgItem', (_message.Message,), {
    'DESCRIPTOR' : _GETUSERLISTREPLY_MSGITEM,
    '__module__' : 'userinfo_pb2'
    # @@protoc_insertion_point(class_scope:UserInfo.GetUserListReply.MsgItem)
    })
  ,
  'DESCRIPTOR' : _GETUSERLISTREPLY,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo.GetUserListReply)
  })
_sym_db.RegisterMessage(GetUserListReply)
_sym_db.RegisterMessage(GetUserListReply.MsgItem)

SaveUserRequest = _reflection.GeneratedProtocolMessageType('SaveUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEUSERREQUEST,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo.SaveUserRequest)
  })
_sym_db.RegisterMessage(SaveUserRequest)

SaveUserReply = _reflection.GeneratedProtocolMessageType('SaveUserReply', (_message.Message,), {
  'DESCRIPTOR' : _SAVEUSERREPLY,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo.SaveUserReply)
  })
_sym_db.RegisterMessage(SaveUserReply)


DESCRIPTOR._options = None

_USERINFOSERVICE = _descriptor.ServiceDescriptor(
  name='UserInfoService',
  full_name='UserInfo.UserInfoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=450,
  serialized_end=671,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetList',
    full_name='UserInfo.UserInfoService.GetList',
    index=0,
    containing_service=None,
    input_type=_GETUSERLISTREQUEST,
    output_type=_GETUSERLISTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetById',
    full_name='UserInfo.UserInfoService.GetById',
    index=1,
    containing_service=None,
    input_type=_GETUSERBYIDREQUEST,
    output_type=_GETUSERBYIDRELPY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Save',
    full_name='UserInfo.UserInfoService.Save',
    index=2,
    containing_service=None,
    input_type=_SAVEUSERREQUEST,
    output_type=_SAVEUSERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERINFOSERVICE)

DESCRIPTOR.services_by_name['UserInfoService'] = _USERINFOSERVICE

# @@protoc_insertion_point(module_scope)
